// Latest movies
export const FETCH_MOVIES_LATEST = 'FETCH_MOVIES_LATEST';
export const FETCH_MOVIES_LATEST_SUCCESS = 'FETCH_MOVIES_LATEST_SUCCESS';
export const FETCH_MOVIES_LATEST_FAILURE = 'FETCH_MOVIES_LATEST_FAILURE';

// Movies search
export const FETCH_MOVIES_SEARCH = 'FETCH_MOVIES_SEARCH';
export const FETCH_MOVIES_SEARCH_SUCCESS = 'FETCH_MOVIES_SEARCH_SUCCESS';
export const FETCH_MOVIES_SEARCH_FAILURE = 'FETCH_MOVIES_SEARCH_FAILURE';

// Movie details
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE';

// Popup message
export const SHOW_POPUP_MESSAGE = 'SHOW_POPUP_MESSAGE';
export const HIDE_POPUP_MESSAGE = 'HIDE_POPUP_MESSAGE';